version: "3.3"  # optional since v1.27.0
services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
        -   8098:80
        links:
            -   fpm
        volumes:
            - ./:/var/www/project-docker
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
        -   ./:/var/www/project-docker
        links:
            -   mysql
    mysql:
        image: mysql:5.7
        ports:
        -   33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=laravel
        volumes:
            - ~/volumes/MyProject/mysql/:/var/lib/mysql/

